HOST="localhost"
USER="root"
PASSWORD="Test123#"
PORT=3305
DATABASE="Accounting"

CONSUMER_ENDPOINT = "http://localhost:8080/consumer/"
RESTAURANT_ENDPOINT = "http://localhost:8081/restaurant/"
ORDER_ENDPOINT = "http://localhost:8082/order/"